### ISSUE TITLE
Provide Demo video / gif

### ISSUE THREAD

**Issue by Gustl22** [codesyncapp/codesync-vs#1]
I haven't tried your plugin yet. I also use IntelliJ
But I was pretty exited as this plugin claims to sync the code instead of sharing it, even better would be with a real-time P2P connection to avoid storing the code on a server.

You may can provide a demo video that users can see the plugin in action? Thank you!

**Comment by Basit-qc** [comment]
@Gustl22 Thanks for reaching out. README has been updated: https://github.com/codesyncapp/codesync-vs/blob/master/README.md

**Comment by Gustl22** [comment]
Nice thanks for your work. Will try it out :)
